---
title: "Service"
---

# Community

## SAPEC

I am proud to be a member of [SAPEC](https://sea-paleo.github.io) (Southeast Asia Paleo Environment Consortium), an initiative led by my mentor, Dr. Brendan Buckley. SAPEC is a group of scientists studying the paleoclimate, paleoenvironment, and history of Southeast Asia.

## PAGES

I have been a Regional Representative for the PAGES Early Career Network since 2019. As an RR, I connect early career researchers (ECRs) in the region and promote PAGES activities.

# Conferences and field school organized

-   *SAPEC-2020 Data and Methods in Paleo Proxy Science*\
    Organizing team member\
    Field school with 40 scientists and students from 12 countries.

-   *ESD Summer Conference Series*\
    Founder and lead organizer\
    Student-led annual conferences showcasing research in Engineering Systems & Design

# Peer review

Reviewer for *Quaternary Science Review, Water Resources Research, Journal of Water Resources Planning and Management, Environmental Modelling & Software*, and *Water Management*.
