---
title: "Teaching & Talks"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Teaching

-   Teaching Associate, Columbia University (invited, remotely), Fall 2020\
    Course: Predicting the Effects of Climate Change on Global Forests

**Student's feedback**

> Having Hung as the "TA" was like having a second professor in the course. Hung managed to take a class of total programming beginners and turn most of them into enthusiastic R amateurs. The evidence was that half of the final projects contained an R analysis done by student choice. Hung is an absolute R wizard but also understands the underlying climate dynamics, which makes for a powerful combination. The combination of understanding the data and the ability to use an efficient statistical tool to do an analysis of millions of data is an incredibly powerful tool to give to climate science students. Hung made himself available on short notice and patiently but efficiently taught students not just how to complete assignments, but how to approach climate data analysis. I also got to see Hung in action brilliantly defending his doctoral thesis and can say that whoever gets Hung on their faculty will be very lucky.

-   Graduate Teaching Assistant, SUTD, 2016--2018\
    Courses: Engineering Systems Architecture, Quality and Reliability

# Guest lectures

-   *Dendrochronological data analysis with R*\
    GE5211 Dynamic Environments, National University of Singapore\
    Invited by Dr. Gretchen Coffman

# Invited talks

## Academic

-   *Streamflow variability in Monsoon Asia over the past eight centuries*\
    Woods Hole Oceanographic Institution\
    Tree Ring Lab, Lamont-Doherty Earth Observatory, Columbia University\
    Earth Observatory of Singapore & Asian School of Environment, Nanyang Technological University\
    Centre for Climate Research Singapore

-   *A linear dynamical systems approach to streamflow reconstruction*\
    Centre for Climate Research Singapore

## Industrial

-   *Building trust: An engineer's non-engineering challenge*\
    Singapore University of Technology and Design

# Conferences and workshops

-   AGU 2020 (American Geophysical Union)
-   MODSIM 2019 (Modelling & Simulation Society of Australia and New Zealand)
-   AOGS 2019 (Asia Oceania Geosciences Society)
-   EGU 2019 (European Geosciences Union)
-   SAPEC-2019 Isotopes in the Environment
-   AGU 2018
-   29th European Dendroecological Field Week, 2018
-   EGU 2018
-   AOGS 2017

<aside>

[Video](https://www.dropbox.com/s/rloje2brbyn0isx/agu-2020-%20PP033-05-hung.mp4?dl=0)

</aside>
